### ISSUE TITLE
Generating game rig from rigify control rig give unwanted hierarchy

### ISSUE THREAD

**Issue by shrinktofit** [BlenderBoi/Game-Rig-Tools#2]
Metarig:

<img width="334" alt="image" src="https://github.com/BlenderBoi/Game_Rig_Tools/assets/28807867/8329cfba-1cc2-4577-9faf-10d9aedcfa87">

Rigify generated control rig:

<img width="319" alt="image" src="https://github.com/BlenderBoi/Game_Rig_Tools/assets/28807867/e961c559-91b9-46d8-915b-deb936a99fa5">

Game rig, generated by this addon from rigify generated control rig:

<img width="337" alt="image" src="https://github.com/BlenderBoi/Game_Rig_Tools/assets/28807867/400a7d85-fccc-4044-85c3-55302663acbe">

The problem is game rig is not consistent with meta rig. For example, `(DEF-)mixamorig:LeftUpLeg` should be child of `(DEF-)mixamorig:Hips`. Could I indicate this addon to generate according to metarig?

Any help would be appreciated.

**Comment by BlenderBoi** [comment]
Hi, game rig tools does not do any reparenting
It only extract the deform bone and remove the constraint, and it does not check the metarig 

This means that you will need to reparent some of the bones

And rigify specifically will have this problem
